# Generated by Django 3.2.6 on 2021-08-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_product', models.IntegerField()),
                ('description', models.CharField(max_length=150)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(max_length=150)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
